# Generated by Django 4.1.5 on 2023-03-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_clinic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=130),
        ),
    ]
