# Generated by Django 4.1.5 on 2023-02-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentistRoll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='clinic',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='manager',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
