# Generated by Django 4.1.5 on 2023-02-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DentistRoll', '0002_dentist_code_alter_dentist_clinic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentist',
            old_name='contact',
            new_name='number',
        ),
    ]
