# Generated by Django 4.1.5 on 2023-02-03 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DentistRoll', '0004_remove_dentist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
