# Generated by Django 4.1.5 on 2023-02-03 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerRoll', '0002_alter_manager_user'),
        ('DentistRoll', '0005_alter_dentist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ManagerRoll.manager'),
        ),
    ]
