# Generated by Django 4.1.5 on 2023-02-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentistRoll', '0006_alter_dentist_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('building_number', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=150)),
                ('town', models.CharField(max_length=150)),
                ('postcode', models.IntegerField()),
                ('country', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Clinics',
            },
        ),
    ]
