# Generated by Django 4.1.5 on 2023-02-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentistRoll', '0007_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentist',
            name='clinic',
        ),
        migrations.AddField(
            model_name='dentist',
            name='clinic',
            field=models.ManyToManyField(to='DentistRoll.clinic'),
        ),
    ]
