# Generated by Django 4.1.5 on 2023-02-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentistRoll', '0008_remove_dentist_clinic_dentist_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='clinic',
            field=models.ManyToManyField(blank=True, null=True, to='DentistRoll.clinic'),
        ),
    ]
