# Generated by Django 4.1.5 on 2023-02-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentistRoll', '0009_alter_dentist_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='postcode',
            field=models.CharField(max_length=150),
        ),
    ]
