# Generated by Django 4.1.5 on 2023-03-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentistRoll', '0010_alter_clinic_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='clinic',
            field=models.ManyToManyField(to='DentistRoll.clinic'),
        ),
    ]
