# Generated by Django 4.1.5 on 2023-03-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicRoll', '0001_initial'),
        ('Case', '0013_alter_case_clinic'),
        ('DentistRoll', '0012_alter_dentist_clinic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinic',
        ),
        migrations.AlterField(
            model_name='dentist',
            name='clinic',
            field=models.ManyToManyField(to='ClinicRoll.clinic'),
        ),
    ]
