# Generated by Django 4.1.5 on 2023-03-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicRoll', '0001_initial'),
        ('DentistRoll', '0013_delete_clinic_alter_dentist_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='clinic',
            field=models.ManyToManyField(blank=True, null=True, to='ClinicRoll.clinic'),
        ),
    ]
