# Generated by Django 4.1.5 on 2023-03-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DentistRoll', '0014_alter_dentist_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
