# Generated by Django 4.1.5 on 2023-03-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DentistRoll', '0016_alter_dentist_clinic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentist',
            old_name='code',
            new_name='discount',
        ),
    ]
