# Generated by Django 4.1.5 on 2023-02-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
