# Generated by Django 4.1.5 on 2023-02-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0004_case_totel_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='manager_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='planner_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='technician_paid',
            field=models.BooleanField(default=False),
        ),
    ]
