# Generated by Django 4.1.5 on 2023-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0007_case_refinement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='refinement',
            field=models.IntegerField(default=0),
        ),
    ]
