# Generated by Django 4.1.5 on 2023-03-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0008_alter_case_refinement'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='optional_treatment',
            field=models.CharField(blank=True, choices=[('replacement', 'replacement'), ('mouthguard', 'mouthguard'), ('smile_design', 'smile_design')], max_length=100, null=True),
        ),
    ]
