# Generated by Django 4.1.5 on 2023-03-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0009_case_optional_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='optional_treatment',
            field=models.CharField(blank=True, choices=[('replacement', 'replacement'), ('mouthguard', 'mouthguard'), ('smile design', 'smile design')], max_length=100, null=True),
        ),
    ]
