# Generated by Django 4.1.5 on 2023-03-28 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicRoll', '0001_initial'),
        ('Case', '0010_alter_case_optional_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ClinicRoll.clinic'),
        ),
    ]
