# Generated by Django 4.1.5 on 2023-03-28 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DentistRoll', '0012_alter_dentist_clinic'),
        ('Case', '0011_alter_case_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='DentistRoll.clinic'),
        ),
    ]
