# Generated by Django 4.1.5 on 2023-02-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_plan', models.FloatField(default=0.0)),
                ('fee_retainer', models.FloatField(default=0.0)),
                ('fee_aligner', models.FloatField(default=0.0)),
                ('fee_monitring', models.FloatField(default=0.0)),
                ('fee_comprehensive', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Fee',
            },
        ),
    ]
