# Generated by Django 4.1.5 on 2023-02-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminRoll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_aligner',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_comprehensive',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_monitring',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_plan',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_retainer',
            field=models.IntegerField(default=0.0),
        ),
    ]
