# Generated by Django 4.1.5 on 2023-02-06 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ManagerRoll', '0002_alter_manager_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('building_number', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=150)),
                ('town', models.CharField(max_length=150)),
                ('postcode', models.IntegerField()),
                ('country', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Saloons',
            },
        ),
        migrations.CreateModel(
            name='Saloon_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=150, null=True)),
                ('number', models.CharField(blank=True, max_length=150, null=True)),
                ('code', models.CharField(blank=True, max_length=150, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ManagerRoll.manager')),
                ('saloon', models.ManyToManyField(blank=True, null=True, to='SaloonRoll.saloon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saloon Owners',
            },
        ),
    ]
