# Generated by Django 4.1.5 on 2023-02-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaloonRoll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloon',
            name='postcode',
            field=models.CharField(max_length=150),
        ),
    ]
